name: Update targetRevision do job and Revert

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Requires to be able to push to the origin repository
permissions:
  contents: write

# 3 jobs to be done
# Update targetRevision
# Do some work with modified repository
# Revert the change back
jobs:
  # Modifiying the Target Revision
  adjustTargetRevision:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Modify Target Revision
        run: |
          echo There is a GIT hash of the latest commit on main branch:
          T_HASH=`git show HEAD --pretty=format:"%H" --no-patch`
          echo $T_HASH
          sed -i -e "s/    targetRevision: main/    targetRevision: $T_HASH/g" ./folder_1/folder_2/file_name.yml
          git diff
          
          git config user.name 'GitHub'
          git config user.email 'noreply@github.com'
          git commit -am "Update Target Revision"
          git push

  # Job to do tasks with modified main branch
  doWork:
    runs-on: ubuntu-latest
    # Execute after adjustTargetRevision
    needs: adjustTargetRevision
    steps:
      - uses: actions/checkout@v3
        with:
          repository: hasys/test-github-actions
          ref: refs/heads/main
      - name: Do some work
        run: |
          cat ./folder_1/folder_2/file_name.yml

  # Revert the change, make the Target Revision main again
  cleanUp:
    runs-on: ubuntu-latest
    needs: doWork
    steps:
      - uses: actions/checkout@v3
      - name: Revert the Target Revision value
        run: |
          git pull --rebase origin main
          T_HASH=`git show HEAD~1 --pretty=format:"%H" --no-patch`
          echo $T_HASH
          sed -i -e "s/    targetRevision: $T_HASH/    targetRevision: main/g" ./folder_1/folder_2/file_name.yml  
          
          git config user.name 'GitHub'
          git config user.email 'noreply@github.com'
          git commit -am "Revert changes"
          git push
          
